name: load-test

on:
  workflow_dispatch:

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install packet-python
          sudo apt-get install python3-setuptools

      - name: Install Ansible
        run: sudo pip3 install ansible

      - name: Retrieve dynamic inventory script
        run: |
          wget https://github.com/ansible/ansible/raw/stable-2.9/contrib/inventory/packet_net.py
          sed -i 's/#!\/usr\/bin\/env python/#!\/usr\/bin\/env python3/' packet_net.py
          wget https://github.com/ansible/ansible/raw/stable-2.9/contrib/inventory/packet_net.ini

      - name: Debug
        run: |
          cat packet_net.py
          pip3 list
          ansible --version

      - name: Get inventory from packet
        run: PACKET_API_TOKEN=${{ secrets.PACKET_API_TOKEN }} python3 packet_net.py --list